# Generated by Django 4.2.8 on 2023-12-09 03:05

import ancilla_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ancilla_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("author", models.CharField(max_length=80)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("M", "Mystery"),
                            ("B", "Biography/Autobiography"),
                            ("F", "Fantasy"),
                            ("H", "Historical Fiction"),
                            ("P", "Poetry"),
                            ("R", "Romance"),
                            ("S", "Science Fiction"),
                            ("T", "Thriller/Suspense"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("address", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=10)),
                (
                    "expire_date",
                    models.DateField(
                        blank=True, default=ancilla_app.models.two_years_from_now
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hold_date", models.DateField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ancilla_app.book",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ancilla_app.patron",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_date", models.DateField(auto_now_add=True)),
                (
                    "due_date",
                    models.DateField(
                        blank=True, default=ancilla_app.models.three_weeks_from_now
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ancilla_app.book",
                    ),
                ),
                (
                    "patron",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ancilla_app.patron",
                    ),
                ),
            ],
        ),
    ]
