# Generated by Django 4.2.8 on 2023-12-09 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ancilla_app", "0002_book_patron_hold_checkout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="title",
        ),
    ]
